# Generated by Django 3.2.5 on 2021-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.JSONField(default=list),
        ),
    ]
