# Generated by Django 3.2.5 on 2021-07-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'This username has already been registered.'}, max_length=100, null=True, unique=True, verbose_name='username'),
        ),
    ]
