# Generated by Django 3.2.5 on 2021-07-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='age'),
        ),
    ]
