# Generated by Django 3.2.5 on 2021-07-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20210730_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.JSONField(default={}),
        ),
    ]
