# Generated by Django 3.2.5 on 2021-08-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_contact_primaryphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
