# Generated by Django 3.2.5 on 2021-08-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_alter_contact_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='primaryPhone',
            new_name='primary_phone',
        ),
    ]
